#!/usr/bin/env python3
"""Make the `bpy` pip module importable on a minimal Linux container.

Blender's Python module ships its own copies of most dependencies, but it still
has DT_NEEDED entries on system X11/GL libraries that a slim container does not
have (libXrender, libXi, libXfixes, libSM, libICE, libXt, libxkbcommon,
libGL/libGLX/libOpenGL).

When running headless -- registering addon classes, running operators, editing
data, rendering with Cycles/EEVEE-NG to a file -- none of that windowing code is
ever executed. The dynamic linker still refuses to load the module until those
libraries exist and export the referenced symbols, so we:

  1. create empty stub shared objects with the right SONAMEs, and
  2. build one preloaded shim exporting exactly the symbols the loader reports
     as missing, discovered iteratively.

If a stubbed symbol is ever actually *called*, it returns garbage and the
process will crash or misbehave. That is why this is a testing aid, not a
substitute for validating UI/viewport work in a real desktop Blender.

Usage:  python3 tools/build_bpy_shim.py [target_dir] [--python /path/to/python]
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys

STUB_SONAMES = [
    "libGL.so.1",
    "libGLX.so.0",
    "libOpenGL.so.0",
    "libICE.so.6",
    "libSM.so.6",
    "libXfixes.so.3",
    "libXi.so.6",
    "libXrender.so.1",
    "libXt.so.6",
    "libxkbcommon.so.0",
]

UNDEF_RE = re.compile(r"undefined symbol: ([A-Za-z0-9_.@$]+)(?:, version ([A-Za-z0-9_.]+))?")


def gcc() -> str:
    for cand in ("gcc", "cc", "clang"):
        found = shutil.which(cand)
        if found:
            return found
    raise SystemExit("no C compiler found; install gcc to build the shim")


def build_stubs(target: str) -> None:
    libdir = os.path.join(target, "lib")
    os.makedirs(libdir, exist_ok=True)
    tmp_c = os.path.join(target, "_stub.c")
    with open(tmp_c, "w") as fh:
        fh.write("void _bpy_stub_placeholder(void) {}\n")
    for soname in STUB_SONAMES:
        out = os.path.join(libdir, soname)
        if os.path.exists(out):
            continue
        subprocess.run(
            [gcc(), "-shared", "-fPIC", "-O0", "-w", f"-Wl,-soname,{soname}", "-o", out, tmp_c],
            check=True,
        )
    os.remove(tmp_c)


def write_shim(target: str, syms: dict[str, str | None]) -> None:
    """Emit shim.so exporting every symbol in `syms` (value = version node)."""
    nodes: dict[str, list[str]] = {}
    for sym, ver in syms.items():
        nodes.setdefault(ver or "", []).append(sym)

    src = ["/* generated by tools/build_bpy_shim.py -- do not edit */"]
    version_clauses = []
    for ver, names in sorted(nodes.items()):
        for name in sorted(names):
            src.append(f"void {name}(void) {{}}")
        if ver:
            version_clauses.append(f"{ver} {{ global: " + "; ".join(sorted(names)) + "; };")

    c_path = os.path.join(target, "shim.c")
    map_path = os.path.join(target, "shim.map")
    with open(c_path, "w") as fh:
        fh.write("\n".join(src) + "\n")
    with open(map_path, "w") as fh:
        fh.write("\n".join(version_clauses) + "\nSHIM_1.0 { global: *; };\n")

    subprocess.run(
        [
            gcc(), "-shared", "-fPIC", "-O0", "-w",
            "-o", os.path.join(target, "shim.so"),
            c_path, f"-Wl,--version-script={map_path}",
        ],
        check=True,
    )


def env_for(target: str, base: dict[str, str] | None = None) -> dict[str, str]:
    env = dict(base if base is not None else os.environ)
    env["LD_PRELOAD"] = os.path.join(target, "shim.so")
    env["LD_LIBRARY_PATH"] = (
        os.path.join(target, "lib") + os.pathsep + env.get("LD_LIBRARY_PATH", "")
    )
    return env


def import_ok(python: str, target: str) -> tuple[bool, str]:
    proc = subprocess.run(
        [python, "-c", "import bpy; print('BPY_OK', bpy.app.version_string)"],
        capture_output=True, text=True, env=env_for(target), timeout=600,
    )
    out = proc.stdout + proc.stderr
    return ("BPY_OK" in out), out


def discover_symbols(python: str, target: str, max_iters: int = 500) -> dict[str, str | None]:
    state_path = os.path.join(target, "syms.json")
    syms: dict[str, str | None] = {}
    if os.path.exists(state_path):
        with open(state_path) as fh:
            syms = json.load(fh)

    for iteration in range(max_iters):
        with open(state_path, "w") as fh:
            json.dump(syms, fh, indent=0, sort_keys=True)
        write_shim(target, syms)
        ok, out = import_ok(python, target)
        if ok:
            print(f"bpy imports cleanly after {iteration} iteration(s); {len(syms)} shimmed symbol(s)")
            return syms
        match = UNDEF_RE.search(out)
        if not match:
            raise SystemExit(f"could not make progress:\n{out[-2000:]}")
        sym, ver = match.group(1), match.group(2)
        if sym in syms:
            raise SystemExit(f"symbol {sym} still unresolved after being shimmed:\n{out[-1200:]}")
        syms[sym] = ver
    raise SystemExit(f"gave up after {max_iters} iterations ({len(syms)} symbols)")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("target", nargs="?", default=os.path.expanduser("~/.bpyshim"))
    ap.add_argument("--python", default=os.path.expanduser("~/.venv/bin/python"),
                    help="interpreter with `bpy` installed")
    args = ap.parse_args()

    if not os.path.exists(args.python):
        raise SystemExit(f"no interpreter at {args.python}")

    os.makedirs(args.target, exist_ok=True)
    build_stubs(args.target)
    syms = discover_symbols(args.python, args.target)

    wrapper = os.path.join(args.target, "run.sh")
    with open(wrapper, "w") as fh:
        fh.write(
            "#!/bin/sh\n"
            f"# Run Python inside real Blender with the X11/GL shim active.\n"
            f"export LD_LIBRARY_PATH={args.target}/lib:$LD_LIBRARY_PATH\n"
            f"export LD_PRELOAD={args.target}/shim.so\n"
            f"exec {args.python} \"$@\"\n"
        )
    os.chmod(wrapper, 0o755)
    print(f"wrote {wrapper}")
    print("shimmed symbols:", ", ".join(sorted(syms)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
